Repository holoviz/holoviews, pull requests merged in 2018-02, with the labels that each got.

#2329 Bumped Travis testing dependencies to latest versions
  .travis.yml
  holoviews/core/data/dask.py
  holoviews/core/data/dictionary.py
  holoviews/operation/datashader.py
  holoviews/plotting/mpl/__init__.py
  tests/testbokehgraphs.py
  tests/testplotinstantiation.py
  tests/testrenderclass.py
Labels: testing

#2336 Fixed bug in bokeh TablePlot not escaping dimensions correctly
  holoviews/plotting/bokeh/tabular.py
  tests/plotting/bokeh/testtabular.py
Labels: bokeh, bug

#2335 Fixed bug handling dask dataframe indexes
  holoviews/core/data/pandas.py
Labels: bug, data

#2138 Add Chord element
  examples/gallery/demos/bokeh/route_chord.ipynb
  examples/gallery/demos/matplotlib/route_chord.ipynb
  examples/reference/elements/bokeh/Chord.ipynb
  examples/reference/elements/matplotlib/Chord.ipynb
  holoviews/element/graphs.py
  holoviews/element/util.py
  holoviews/plotting/bokeh/__init__.py
  holoviews/plotting/bokeh/graphs.py
  holoviews/plotting/mpl/__init__.py
  holoviews/plotting/mpl/graphs.py
  tests/element/testgraphelement.py
  tests/plotting/bokeh/testgraphplot.py
  tests/plotting/matplotlib/testgraphplot.py
Labels: feature

#2344 Datashader fixes
  holoviews/core/util.py
  holoviews/operation/datashader.py
  tests/operation/testdatashader.py
  tests/testcoreutils.py
Labels: bug

#2346 Miscellaneous minor bug fixes
  holoviews/core/traversal.py
  holoviews/element/stats.py
  holoviews/element/util.py
  holoviews/plotting/bokeh/callbacks.py
  holoviews/plotting/bokeh/stats.py
Labels: minor-bug

#1978 Enable situate_axes in matplotlib for consistency
  holoviews/plotting/mpl/raster.py
Labels: mpl, plotting

#2345 Handle range on heterogeneously typed Dataset column
  holoviews/core/data/interface.py
  holoviews/core/data/pandas.py
  holoviews/core/util.py
  tests/core/data/testdataset.py
Labels: bug, data

#2330 Add Element.__contains__ method
  doc/Tutorials/Columnar_Data.ipynb
  examples/user_guide/07-Tabular_Datasets.ipynb
  holoviews/core/element.py
  tests/core/testelement.py
Labels: API, feature

#2363 fixed color option in code snippet
  examples/reference/elements/bokeh/BoxWhisker.ipynb
Labels: docs, minor-bug, options

#2360 Fixed clip parameter on Violin
  holoviews/plotting/bokeh/stats.py
  tests/plotting/bokeh/testviolinplot.py
Labels: API, bokeh

#2357 Decode bytes in bokeh plots
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/plot.py
  holoviews/plotting/bokeh/stats.py
  holoviews/plotting/bokeh/util.py
Labels: bokeh

#2331 Ensured Tree types do not create lowercase node on attribute access
  holoviews/core/tree.py
  tests/core/testtree.py
Labels: bug

#2377 Fixed bug finding Layout label
  holoviews/core/util.py
Labels: bug
