Repository holoviz/holoviews, pull requests merged in 2019-09, with the labels that each got.

#3919 Add LabelledData.dataset property
  holoviews/core/data/__init__.py
  holoviews/core/data/dask.py
  holoviews/core/data/interface.py
  holoviews/core/data/pandas.py
  holoviews/core/dimension.py
  holoviews/element/chart.py
  holoviews/element/stats.py
  holoviews/operation/element.py
  holoviews/tests/core/testdatasetproperty.py
Labels: API, feature

#3973 Various fixes for xarray 0.13 compatibility
  holoviews/core/data/xarray.py
Labels: data

#3977 Correctly resample colorcet colormaps
  holoviews/plotting/util.py
Labels: bug

#3978 Ensure that empty Stream source elements get remapped
  holoviews/streams.py
  holoviews/tests/teststreams.py
Labels: bug

#3989 Fix apply method on HoloMap
  holoviews/core/accessors.py
  holoviews/tests/core/testapply.py
Labels: bug

#3983 Add support for packing grid value dimensions
  holoviews/core/data/grid.py
  holoviews/core/data/interface.py
  holoviews/core/data/xarray.py
  holoviews/element/raster.py
  holoviews/plotting/bokeh/raster.py
  holoviews/tests/core/data/testgridinterface.py
  holoviews/tests/core/data/testxarrayinterface.py
  holoviews/tests/element/testraster.py
Labels: data, enhancement

#3967 Add pipeline property to track data lineage
  holoviews/core/accessors.py
  holoviews/core/data/__init__.py
  holoviews/core/data/interface.py
  holoviews/core/data/multipath.py
  holoviews/core/dimension.py
  holoviews/core/operation.py
  holoviews/element/chart.py
  holoviews/operation/element.py
  holoviews/operation/timeseries.py
  holoviews/plotting/bokeh/stats.py
  holoviews/tests/core/testdatasetproperty.py
  holoviews/tests/operation/testoperation.py
Labels: API, feature

#3992 Ensure tests run without dask and plotly
  holoviews/plotting/renderer.py
  holoviews/tests/core/testdatasetproperty.py
  holoviews/tests/plotting/plotly/testcallbacks.py
  holoviews/tests/plotting/plotly/testdynamic.py
  holoviews/tests/plotting/plotly/testplot.py
  holoviews/tests/plotting/plotly/testrenderer.py
  holoviews/tests/plotting/plotly/testrgb.py
Labels: testing

#3995 Fixed various issues with test imports
  holoviews/tests/core/testdatasetproperty.py
  holoviews/tests/plotting/plotly/testcallbacks.py
  holoviews/tests/plotting/plotly/testrenderer.py
Labels: bug, testing
