Repository holoviz/holoviews, pull requests merged in 2019-05, with the labels that each got.

#3676 Added CHANGELOG for 1.12.2 release
  CHANGELOG.md
  doc/releases.rst
Labels: docs

#3688 Reuse PlotSize stream if it exists
  holoviews/plotting/bokeh/element.py
Labels: bug

#3689 Fixed hv.help() for non-hv objects
  holoviews/__init__.py
Labels: bug

#3727 Ensure RGB hover is handled
  holoviews/plotting/bokeh/raster.py
Labels: bokeh

#3728 Ensure Param streams handle subobject dependencies
  holoviews/streams.py
  holoviews/tests/core/testapply.py
  holoviews/tests/core/testoperation.py
  holoviews/tests/teststreams.py
Labels: bug

#3736 datetime handling for spikes
  holoviews/plotting/mpl/chart.py
Labels: bug, mpl

#3738 Fixed and unified links on Overlay reference page
  examples/reference/containers/bokeh/Overlay.ipynb
  examples/reference/containers/matplotlib/Overlay.ipynb
  examples/reference/containers/plotly/Overlay.ipynb
Labels: docs
