Repository holoviz/holoviews, pull requests merged in 2019-07, with the labels that each got.

#3804 Add MPL 3.1 deprecations to rcparam context manager
  holoviews/plotting/mpl/plot.py
Labels: mpl

#3803 Enable cmap option in matplotlib HexTiles
  holoviews/plotting/mpl/hex_tiles.py
Labels: mpl

#3813 Make matplotlib Bars respect lower ylim if logy=True
  holoviews/plotting/mpl/chart.py
Labels: bug, mpl

#3823 Make Buffer following behavior toggleable
  examples/user_guide/16-Streaming_Data.ipynb
  holoviews/plotting/bokeh/element.py
  holoviews/streams.py
  holoviews/tests/plotting/bokeh/teststreaming.py
Labels: enhancement

#3848 Fixed handling of data_aspect
  examples/user_guide/Plotting_with_Bokeh.ipynb
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/util.py
  holoviews/tests/plotting/bokeh/testelementplot.py
Labels: bug, enhancement

#3809 Fixed legends for PathPlot
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/path.py
  holoviews/tests/plotting/bokeh/testpathplot.py
Labels: bug

#3853 Fix range issues on Bars
  holoviews/plotting/bokeh/chart.py
  holoviews/tests/plotting/bokeh/testbarplot.py
Labels: bug

#3734 Fix setting edge colors for Chord graphs using an explicit mapping
  holoviews/plotting/mpl/element.py
Labels: bug

#3851 Use Panel to generate HTML output
  holoviews/plotting/bokeh/renderer.py
  holoviews/plotting/mpl/renderer.py
  holoviews/plotting/plotly/plotlywidgets.js
  holoviews/plotting/plotly/renderer.py
  holoviews/plotting/renderer.py
Labels: WIP

#3854 Interface improvements for dask and dtype handling
  holoviews/core/data/array.py
  holoviews/core/data/dask.py
  holoviews/core/data/dictionary.py
  holoviews/core/data/image.py
  holoviews/core/data/interface.py
  holoviews/core/data/multipath.py
  holoviews/core/data/pandas.py
  holoviews/core/util.py
  holoviews/operation/element.py
  holoviews/tests/core/data/base.py
  holoviews/tests/core/data/testarrayinterface.py
  holoviews/tests/core/data/testdictinterface.py
  holoviews/tests/core/data/testimageinterface.py
  holoviews/tests/operation/testoperation.py
Labels: data, enhancement

#3860 Optimized axis range and factor finding
  holoviews/core/data/interface.py
  holoviews/core/data/multipath.py
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/plot.py
  holoviews/tests/plotting/bokeh/testelementplot.py
Labels: enhancement
