Repository holoviz/holoviews, pull requests merged in 2019-03, with the labels that each got.

#3536 Fixed bokeh periodic callback
  holoviews/plotting/bokeh/util.py
Labels: bokeh, bug

#3474 Add an apply method to apply functions to elements
  holoviews/core/dimension.py
  holoviews/core/operation.py
  holoviews/core/spaces.py
  holoviews/core/tree.py
  holoviews/core/util.py
  holoviews/streams.py
  holoviews/tests/core/testapply.py
  holoviews/tests/core/testdynamic.py
  holoviews/util/__init__.py
Labels: API, enhancement

#3545 Unified setup.py and meta.yaml
  conda.recipe/meta.yaml
  setup.py
Labels: packaging

#3546 Fixes for dynamic Operation and tests
  holoviews/core/operation.py
  holoviews/tests/core/testoperation.py
Labels: regression

#3556 add radius for node options for bokeh
  holoviews/plotting/bokeh/graphs.py
Labels: bokeh

#3571 Ensure that defaults set color not fill_color
  holoviews/plotting/bokeh/__init__.py
Labels: ready

#3554 Allow using apply method with method strings
  holoviews/core/accessors.py
  holoviews/core/data/__init__.py
  holoviews/core/dimension.py
  holoviews/core/options.py
  holoviews/core/spaces.py
  holoviews/element/graphs.py
  holoviews/tests/core/testapply.py
Labels: API, feature

#3450 Compatibility with bokeh layout refactor
  .appveyor.yml
  .travis.yml
  examples/user_guide/Plotting_with_Bokeh.ipynb
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/plot.py
  holoviews/plotting/bokeh/renderer.py
  holoviews/plotting/bokeh/tabular.py
  holoviews/plotting/bokeh/util.py
  holoviews/plotting/mpl/element.py
  holoviews/plotting/mpl/raster.py
  holoviews/tests/plotting/bokeh/testelementplot.py
  holoviews/tests/plotting/bokeh/testgridplot.py
  holoviews/tests/plotting/bokeh/testlayoutplot.py
  holoviews/tests/plotting/bokeh/testrenderer.py
  setup.py
Labels: bokeh

#3575 Fixes when specifying both data_aspect and responsive modes
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/util.py
  holoviews/tests/plotting/bokeh/testelementplot.py
Labels: bug

#3578 Improved support for style mapping constant values
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/mpl/element.py
  holoviews/tests/plotting/bokeh/testcurveplot.py
  holoviews/tests/plotting/matplotlib/testcurveplot.py
Labels: enhancement, plotting

#3574 Switch to HTML mime bundle
  holoviews/ipython/display_hooks.py
  setup.py
Labels: notebook

#3580 Ensure Dimension clone copies all parameters
  holoviews/core/dimension.py
Labels: bug

#3517 Add clabel param
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/mpl/element.py
Labels: feature

#3481 Removed Aliases utility
  holoviews/core/util.py
  holoviews/tests/core/testaliases.py
  holoviews/util/__init__.py
Labels: API

#3585 Ensure that explicit tick lookup of floats works in JS
  holoviews/plotting/bokeh/element.py
Labels: ready

#3590 Colorscale/colorbar fixes for Plotly backend
  holoviews/plotting/plotly/chart3d.py
  holoviews/plotting/plotly/element.py
  holoviews/plotting/plotly/stats.py
  holoviews/plotting/plotly/util.py
  holoviews/tests/plotting/plotly/testbivariateplot.py
  holoviews/tests/plotting/plotly/testsurfaceplot.py
Labels: plotting
