Repository holoviz/holoviews, pull requests merged in 2019-08, with the labels that each got.

#3911 Regrid doc elaboration for image data
  examples/user_guide/15-Large_Data.ipynb
Labels: docs

#3197 Implement datetime selections as strings and datetimes
  holoviews/core/data/grid.py
  holoviews/core/data/interface.py
  holoviews/core/util.py
  holoviews/element/chart.py
  holoviews/tests/element/testelementselect.py
Labels: feature

#3916 Fixed GridSpace axis alignment
  holoviews/plotting/bokeh/util.py
Labels: bug

#3915 Refactored datashader operations and add new aggregators
  examples/user_guide/15-Large_Data.ipynb
  holoviews/operation/datashader.py
  holoviews/tests/operation/testdatashader.py
Labels: feature
