Repository holoviz/holoviews, pull requests merged in 2019-02, with the labels that each got.

#3453 Ensure all tests pass without pandas, dask, xarray and scipy
  holoviews/core/data/__init__.py
  holoviews/core/data/dask.py
  holoviews/core/data/dictionary.py
  holoviews/core/util.py
  holoviews/element/raster.py
  holoviews/operation/element.py
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/stats.py
  holoviews/plotting/mpl/chart.py
  holoviews/plotting/util.py
  holoviews/tests/core/data/base.py
  holoviews/tests/core/data/testdaskinterface.py
  holoviews/tests/core/data/testgridinterface.py
  holoviews/tests/core/data/testmultiinterface.py
  holoviews/tests/core/data/testpandasinterface.py
  holoviews/tests/core/data/testxarrayinterface.py
  holoviews/tests/core/testndmapping.py
  holoviews/tests/core/testoptions.py
  holoviews/tests/core/teststoreoptions.py
  holoviews/tests/core/testutils.py
  holoviews/tests/element/testgraphelement.py
  holoviews/tests/element/teststatselements.py
  holoviews/tests/operation/testdatashader.py
  holoviews/tests/operation/testoperation.py
  holoviews/tests/operation/testtimeseriesoperations.py
  holoviews/tests/plotting/bokeh/testcurveplot.py
  holoviews/tests/plotting/bokeh/testpointplot.py
  holoviews/tests/plotting/bokeh/testrenderer.py
  holoviews/tests/plotting/bokeh/testspikesplot.py
  holoviews/tests/plotting/bokeh/testutils.py
  holoviews/tests/plotting/bokeh/testviolinplot.py
  holoviews/tests/plotting/matplotlib/testcurveplot.py
  holoviews/tests/plotting/matplotlib/testrenderer.py
  holoviews/tests/plotting/matplotlib/testwidgets.py
  holoviews/tests/plotting/plotly/testplot.py
  holoviews/tests/plotting/testcomms.py
  holoviews/tests/plotting/testplotutils.py
  holoviews/tests/teststreams.py
Labels: testing

#3460 Fixed datetime handling in datashade operations on dask dataframe
  holoviews/operation/datashader.py
  holoviews/tests/operation/testdatashader.py
Labels: bug

#3444 Attempt updating to new build infrastructure
  .appveyor.yml
  .travis.yml
  conda.recipe/meta.yaml
  dodo.py
  holoviews/core/data/grid.py
  holoviews/plotting/plotly/chart.py
  holoviews/tests/plotting/bokeh/testrenderer.py
  setup.py
  tox.ini
Labels: packaging, testing

#3445 Apply Labels offset using bokeh transform
  holoviews/plotting/bokeh/annotation.py
Labels: bokeh, enhancement

#3475 Fix clip transformation for dim function
  holoviews/util/transform.py
Labels: bug

#3479 Ensure Image coordinates are rectilinear
  holoviews/element/raster.py
  holoviews/tests/element/testimage.py
Labels: bug

#3478 Retain Element._plot_id on redim
  holoviews/core/dimension.py
Labels: bug

#3477 Fixed unclosed paths on polygons
  .travis.yml
  holoviews/plotting/mpl/util.py
  holoviews/tests/plotting/matplotlib/testpathplot.py
  holoviews/tests/plotting/matplotlib/testutils.py
Labels: bug, mpl

#3476 Fixed ArrowPlot and added tests
  holoviews/plotting/bokeh/annotation.py
  holoviews/plotting/bokeh/element.py
  holoviews/tests/plotting/bokeh/testannotationplot.py
Labels: bokeh, bug

#3488 Fix mistake in VectorField's angle conversion if invert_axes
  holoviews/plotting/bokeh/chart.py
Labels: bokeh, bug

#3490 Fixed Param stream memoization
  holoviews/streams.py
  holoviews/tests/teststreams.py
Labels: bug

#3491 Enable the use of xlim parameter for timeseries plots
  holoviews/plotting/plot.py
Labels: enhancement

#3495 Implement optimized TriMesh wireframe rendering
  holoviews/operation/datashader.py
  holoviews/tests/operation/testdatashader.py
Labels: enhancement

#3507 Build gallery on travis
  .travis.yml
Labels: docs

#3511 Test that all elements support empty constructors
  holoviews/core/data/grid.py
  holoviews/element/annotation.py
  holoviews/element/chart.py
  holoviews/element/graphs.py
  holoviews/element/raster.py
  holoviews/element/sankey.py
  holoviews/element/tabular.py
  holoviews/plotting/bokeh/sankey.py
  holoviews/tests/element/testelementconstructors.py
Labels: testing

#3515 Added Tiles element from geoviews
  examples/reference/elements/bokeh/Tiles.ipynb
  holoviews/element/__init__.py
  holoviews/element/tiles.py
  holoviews/plotting/bokeh/__init__.py
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/tiles.py
  holoviews/tests/element/testelementconstructors.py
Labels: feature

#3519 Fixed datetime out of bounds issues on callbacks
  holoviews/plotting/bokeh/callbacks.py
  holoviews/tests/plotting/bokeh/testcallbacks.py
Labels: bokeh, bug

#3520 Implement datetime hover for Raster/Image types
  holoviews/plotting/bokeh/raster.py
Labels: bokeh, enhancement

#3524 Handle Graph node_color correctly
  examples/reference/elements/bokeh/Graph.ipynb
  holoviews/plotting/bokeh/__init__.py
  holoviews/plotting/bokeh/graphs.py
Labels: bokeh, bug

#3525 Updated CHANGELOG for 1.11.3
  CHANGELOG.md
  doc/releases.rst
Labels: docs, packaging

#3526 Test doc checkout
  doc/_templates/layout.html
  doc/conf.py
Labels: docs
