Repository holoviz/holoviews, pull requests merged in 2019-10, with the labels that each got.

#3951 Add link_selections function for automated linked selections
  holoviews/plotting/bokeh/chart.py
  holoviews/plotting/bokeh/plot.py
  holoviews/plotting/bokeh/selection.py
  holoviews/plotting/bokeh/stats.py
  holoviews/plotting/plot.py
  holoviews/plotting/plotly/chart.py
  holoviews/plotting/plotly/chart3d.py
  holoviews/plotting/plotly/selection.py
  holoviews/plotting/plotly/stats.py
  holoviews/plotting/plotly/tabular.py
  holoviews/selection.py
  holoviews/tests/testselection.py
Labels: feature

#3532 Segments
  .gitignore
  examples/reference/elements/bokeh/Segments.ipynb
  examples/reference/elements/matplotlib/Segments.ipynb
  holoviews/core/data/interface.py
  holoviews/element/__init__.py
  holoviews/element/chart.py
  holoviews/element/geom.py
  holoviews/operation/datashader.py
  holoviews/plotting/bokeh/__init__.py
  holoviews/plotting/bokeh/chart.py
  holoviews/plotting/mpl/__init__.py
  holoviews/plotting/mpl/chart.py
  holoviews/tests/operation/testdatashader.py
Labels: feature

#4000 Add new annotations, HSpan, VSpan
  examples/reference/elements/bokeh/HLine.ipynb
  examples/reference/elements/bokeh/HSpan.ipynb
  examples/reference/elements/bokeh/VLine.ipynb
  examples/reference/elements/bokeh/VSpan.ipynb
  examples/reference/elements/matplotlib/HLine.ipynb
  examples/reference/elements/matplotlib/HSpan.ipynb
  examples/reference/elements/matplotlib/VLine.ipynb
  examples/reference/elements/matplotlib/VSpan.ipynb
  examples/reference/elements/plotly/HSpan.ipynb
  examples/reference/elements/plotly/VSpan.ipynb
  holoviews/core/util.py
  holoviews/element/annotation.py
  holoviews/element/comparison.py
  holoviews/plotting/bokeh/__init__.py
  holoviews/plotting/bokeh/annotation.py
  holoviews/plotting/mpl/__init__.py
  holoviews/plotting/mpl/annotation.py
  holoviews/plotting/plotly/__init__.py
  holoviews/plotting/plotly/shapes.py
  holoviews/tests/plotting/bokeh/testannotationplot.py
Labels: feature

#3410 Made shared_axes option supported generally and toggle axiswise when disabled
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/mpl/plot.py
  holoviews/plotting/plot.py
  holoviews/plotting/plotly/plot.py
  holoviews/tests/plotting/bokeh/testlayoutplot.py
  holoviews/tests/plotting/matplotlib/testlayoutplot.py
Labels: enhancement, plotting

#3510 Add Slope annotation
  examples/reference/elements/bokeh/Slope.ipynb
  examples/reference/elements/matplotlib/Slope.ipynb
  holoviews/element/annotation.py
  holoviews/plotting/bokeh/__init__.py
  holoviews/plotting/bokeh/annotation.py
  holoviews/plotting/bokeh/chart.py
  holoviews/plotting/mpl/__init__.py
  holoviews/plotting/mpl/annotation.py
  holoviews/tests/plotting/bokeh/testannotationplot.py
  holoviews/tests/plotting/bokeh/testlayoutplot.py
Labels: feature

#4017 Add support for rendering bokeh and plotly plots as gifs
  holoviews/plotting/bokeh/renderer.py
  holoviews/plotting/plotly/renderer.py
Labels: bokeh, enhancement

#4025 Fix issues in .apply dynamic handling
  holoviews/core/accessors.py
Labels: bug

#4027 Fixes for user guides
  examples/user_guide/15-Large_Data.ipynb
  examples/user_guide/17-Dashboards.ipynb
Labels: docs

#4020 Add support for fast QuadMesh rasterization
  holoviews/core/data/__init__.py
  holoviews/core/data/interface.py
  holoviews/operation/datashader.py
  holoviews/tests/operation/testdatashader.py
Labels: enhancement

#4028 Allow passing widget as dependency
  holoviews/core/util.py
  holoviews/util/__init__.py
Labels: enhancement

#4031 Fixed issues with matplotlib AxesImage legend
  holoviews/plotting/mpl/element.py
Labels: bug, mpl

#4036 Fixed compatibility with new bokeh 1.4 legend options
  holoviews/plotting/bokeh/annotation.py
  holoviews/plotting/bokeh/chart.py
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/graphs.py
  holoviews/plotting/bokeh/path.py
  holoviews/plotting/bokeh/stats.py
Labels: bokeh

#4049 Correctly detect depends fn dependencies
  holoviews/streams.py
  holoviews/tests/teststreams.py
  holoviews/util/__init__.py
Labels: bug
