Repository holoviz/holoviews, pull requests merged in 2020-11, with the labels that each got.

#4592 [WIP] Move to GH Actions
  .appveyor.yml
  .github/workflows/test.yml
  .travis.yml
  holoviews/core/element.py
  holoviews/core/layout.py
  holoviews/element/tabular.py
Labels: status: WIP, tag: component: testing

#4517 Add an IbisInterface
  .github/workflows/test.yml
  .gitignore
  .travis.yml
  binder/environment.yml
  holoviews/core/data/__init__.py
  holoviews/core/data/dask.py
  holoviews/core/data/grid.py
  holoviews/core/data/ibis.py
  holoviews/core/data/interface.py
  holoviews/core/data/xarray.py
  holoviews/core/util.py
  holoviews/element/raster.py
  holoviews/operation/element.py
  holoviews/tests/core/data/testibisinterface.py
  setup.py
Labels: status: WIP, tag: component: data

#4430 Clarify data types accepted by Points
  examples/reference/elements/bokeh/Points.ipynb
  examples/reference/elements/bokeh/TriMesh.ipynb
Labels: tag: docs

#4695 Fix various issues related to data interfaces
  holoviews/core/data/dask.py
  holoviews/selection.py
Labels: type: bug
