Repository holoviz/holoviews, pull requests merged in 2020-01, with the labels that each got.

#4146 Add Rectangles element
  examples/reference/elements/bokeh/Rectangles.ipynb
  examples/reference/elements/matplotlib/Rectangles.ipynb
  examples/reference/streams/bokeh/BoxEdit.ipynb
  examples/user_guide/Annotators.ipynb
  holoviews/annotators.py
  holoviews/element/comparison.py
  holoviews/element/geom.py
  holoviews/plotting/bokeh/__init__.py
  holoviews/plotting/bokeh/callbacks.py
  holoviews/plotting/bokeh/chart.py
  holoviews/plotting/bokeh/geometry.py
  holoviews/plotting/bokeh/graphs.py
  holoviews/plotting/bokeh/path.py
  holoviews/plotting/bokeh/sankey.py
  holoviews/plotting/links.py
  holoviews/plotting/mixins.py
  holoviews/plotting/mpl/__init__.py
  holoviews/plotting/mpl/chart.py
  holoviews/plotting/mpl/geometry.py
  holoviews/plotting/mpl/graphs.py
  holoviews/plotting/mpl/path.py
  holoviews/plotting/plotly/__init__.py
  holoviews/plotting/plotly/chart.py
  holoviews/plotting/plotly/renderer.py
  holoviews/plotting/plotly/shapes.py
  holoviews/streams.py
  holoviews/tests/plotting/bokeh/testcallbacks.py
  holoviews/tests/plotting/plotly/testshapeplots.py
Labels: feature

#3790 New pipe method for more intuitive multidimensional dim transforms
  holoviews/util/transform.py
Labels: enhancement

#4176 Avoid unnecessary casting after MultiInterface.iloc
  holoviews/core/data/multipath.py
Labels: bug, data

#4180 Add support for non-categorical HeatMap
  examples/reference/elements/bokeh/HeatMap.ipynb
  examples/reference/elements/matplotlib/HeatMap.ipynb
  examples/reference/elements/plotly/HeatMap.ipynb
  holoviews/core/data/grid.py
  holoviews/element/raster.py
  holoviews/element/util.py
  holoviews/plotting/bokeh/heatmap.py
  holoviews/plotting/mixins.py
  holoviews/plotting/mpl/__init__.py
  holoviews/plotting/mpl/chart.py
  holoviews/plotting/mpl/heatmap.py
  holoviews/plotting/plotly/raster.py
  holoviews/tests/element/testelementconstructors.py
  holoviews/tests/plotting/bokeh/testheatmapplot.py
  holoviews/tests/plotting/matplotlib/testheatmapplot.py
Labels: ready

#4188 Fixed issues with irregular xarray shape
  holoviews/core/data/xarray.py
  holoviews/tests/core/data/testxarrayinterface.py
Labels: bug, data

#4199 Tab completion via __signature__
  holoviews/ipython/__init__.py
  holoviews/tests/core/testoptions.py
  holoviews/util/__init__.py
  holoviews/util/settings.py
Labels: enhancement, in progress
