Repository holoviz/holoviews, pull requests merged in 2023-11, with the labels that each got.

#5954 Part 1, modernize test suite
  holoviews/core/io.py
  holoviews/element/comparison.py
  holoviews/ipython/__init__.py
  holoviews/tests/conftest.py
  holoviews/tests/core/test_archives.py
  holoviews/tests/core/test_importexport.py
  holoviews/tests/element/test_statselements.py
Labels: tag: component: testing

#5997 Enforce labels
  .github/release.yml
  .github/workflows/labels.yml
Labels: type: maintenance

#5995 Fix hist on overlay
  doc/Homepage.ipynb
  holoviews/operation/element.py
  holoviews/tests/core/test_layouts.py
Labels: type: bug

#6001 Fix Param usage in the Plot and Renderers guide
  examples/user_guide/Plots_and_Renderers.ipynb
Labels: type: docs
