Repository holoviz/holoviews, pull requests merged in 2023-01, with the labels that each got.

#5585 Enable rendering colorbars on bokeh GraphPlots
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/graphs.py
  holoviews/tests/plotting/bokeh/test_graphplot.py
Labels: type: bug, tag: backend: bokeh

#5540 Check for categorical data to histogram
  holoviews/operation/element.py
  holoviews/tests/operation/test_operation.py
Labels: status: ready

#5495 Fix `clim_percentile`
  holoviews/plotting/plot.py
  holoviews/tests/plotting/bokeh/test_elementplot.py
Labels: type: bug

#5418 add scatter3d docs and fix colorbar title
  examples/reference/elements/plotly/Scatter3D.ipynb
  holoviews/element/chart3d.py
  holoviews/plotting/plotly/element.py
  holoviews/tests/plotting/plotly/test_elementplot.py
Labels: status: ready

#5388 Compatibility changes with bokeh 3.0
  .github/workflows/test.yaml
  examples/gallery/demos/bokeh/choropleth_data_link.ipynb
  examples/gallery/demos/bokeh/texas_choropleth_example.ipynb
  examples/gallery/demos/matplotlib/texas_choropleth_example.ipynb
  examples/user_guide/Linked_Brushing.ipynb
  examples/user_guide/Network_Graphs.ipynb
  holoviews/plotting/bokeh/annotation.py
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/graphs.py
  holoviews/plotting/bokeh/links.py
  holoviews/plotting/bokeh/plot.py
  holoviews/plotting/bokeh/util.py
  holoviews/tests/plotting/bokeh/test_barplot.py
  holoviews/tests/plotting/bokeh/test_boxwhiskerplot.py
  holoviews/tests/plotting/bokeh/test_callbacks.py
  holoviews/tests/plotting/bokeh/test_elementplot.py
  holoviews/tests/plotting/bokeh/test_errorbarplot.py
  holoviews/tests/plotting/bokeh/test_graphplot.py
  holoviews/tests/plotting/bokeh/test_gridplot.py
  holoviews/tests/plotting/bokeh/test_hextilesplot.py
  holoviews/tests/plotting/bokeh/test_histogramplot.py
  holoviews/tests/plotting/bokeh/test_labels.py
  holoviews/tests/plotting/bokeh/test_layoutplot.py
  holoviews/tests/plotting/bokeh/test_overlayplot.py
  holoviews/tests/plotting/bokeh/test_pathplot.py
  holoviews/tests/plotting/bokeh/test_pointplot.py
  holoviews/tests/plotting/bokeh/test_renderer.py
  holoviews/tests/plotting/bokeh/test_spikesplot.py
  holoviews/tests/plotting/bokeh/test_vectorfieldplot.py
  holoviews/tests/plotting/bokeh/test_violinplot.py
Labels: status: ready
