Repository holoviz/holoviews, pull requests merged in 2023-12, with the labels that each got.

#6007 Add extra check to detect if we are in jupyterlite
  holoviews/pyodide.py
Labels: type: compatibility

#6026 Compability updates with xarray 2023.12
  holoviews/core/data/xarray.py
  holoviews/tests/core/data/test_xarrayinterface.py
Labels: type: compatibility

#6029 Add 'norm' in init_artists in holoviews/plotting/mpl/raster.py,
  holoviews/plotting/mpl/element.py
  holoviews/plotting/mpl/raster.py
Labels: type: bug

#6003 Fix linking elements that are transformed by a Compositor
  holoviews/plotting/util.py
  holoviews/tests/plotting/bokeh/test_links.py
  holoviews/util/__init__.py
Labels: type: bug

#6030 Override Curve's count aggregator default to `self_intersect=False`
  holoviews/operation/datashader.py
Labels: type: enhancement

#6023 Add datetime hover information for selector
  holoviews/operation/datashader.py
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/raster.py
  holoviews/tests/operation/test_datashader.py
  holoviews/tests/plotting/bokeh/test_rasterplot.py
Labels: type: bug

#6035 Only run test-suite on code change
  .github/workflows/test.yaml
Labels: type: maintenance

#6037 Add skip statement to all steps to work with required
  .github/workflows/test.yaml
Labels: type: maintenance

#6036 Update links and instructions in readme
  .github/workflows/test.yaml
  README.md
Labels: type: maintenance

#6039 Remove custom datetime hover conversion for Bokeh Raster plot
  holoviews/plotting/bokeh/raster.py
  holoviews/plotting/bokeh/util.py
  holoviews/tests/plotting/bokeh/test_rasterplot.py
Labels: type: compatibility

#6038 Fix to broken urls in example gallery pages
  examples/gallery/demos/bokeh/dot_example.ipynb
  examples/gallery/demos/bokeh/histogram_example.ipynb
  examples/gallery/demos/bokeh/iris_example.ipynb
  examples/gallery/demos/bokeh/iris_splom_example.ipynb
  examples/gallery/demos/bokeh/lesmis_example.ipynb
  examples/gallery/demos/bokeh/lorenz_attractor_example.ipynb
  examples/gallery/demos/bokeh/step_chart.ipynb
  examples/gallery/demos/bokeh/stocks_example.ipynb
  examples/gallery/demos/bokeh/texas_choropleth_example.ipynb
  examples/gallery/demos/bokeh/us_unemployment.ipynb
  examples/gallery/demos/matplotlib/histogram_example.ipynb
  examples/gallery/demos/matplotlib/iris_example.ipynb
  examples/gallery/demos/matplotlib/iris_splom_example.ipynb
  examples/gallery/demos/matplotlib/lorenz_attractor_example.ipynb
  examples/gallery/demos/matplotlib/step_chart.ipynb
  examples/gallery/demos/matplotlib/stocks_example.ipynb
  examples/gallery/demos/matplotlib/texas_choropleth_example.ipynb
  examples/gallery/demos/matplotlib/us_unemployment.ipynb
Labels: type: docs

#6040 Add prettier to markdown and yaml
  .github/workflows/build.yaml
  .github/workflows/docs.yaml
  .github/workflows/downstream_tests.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  examples/README.md
  examples/gallery/demos/bokeh/nyc_airport_connections.ipynb
  examples/gallery/demos/matplotlib/nyc_airport_connections.ipynb
  examples/reference/streams/bokeh/Tap.ipynb
Labels: type: maintenance

#6014 Only evaluate `rx` if it is an Reactive Expression
  holoviews/core/spaces.py
  holoviews/tests/core/test_dynamic.py
  holoviews/tests/ui/bokeh/test_callback.py
  holoviews/tests/ui/bokeh/test_layout.py
Labels: type: bug

#6042 Dynamic generate unit test matrix
  .github/workflows/test.yaml
Labels: type: maintenance

#6048 Replace Google Analytics with GoatCounter
  doc/conf.py
  setup.py
Labels: type: docs

#6043 Dynamic generate unit test matrix and add cache option
  .github/workflows/test.yaml
Labels: type: maintenance

#6050 Add true if inputs.cache is not set
  .github/workflows/test.yaml
Labels: type: maintenance
