Repository holoviz/holoviews, pull requests merged in 2024-11, with the labels that each got.

#6429 Fix rasterizing a Path with categorical values including empty strings
  holoviews/operation/datashader.py
  holoviews/tests/operation/test_datashader.py
Labels: type: bug

#6431 compat: Matplotlib 3.10.0
  holoviews/plotting/mpl/stats.py
  holoviews/plotting/mpl/util.py
Labels: type: compatibility

#6433 fix: datashade don't update the dtype of the input DataFrame
  holoviews/operation/datashader.py
  holoviews/tests/operation/test_datashader.py
Labels: type: bug

#6432 docs: Add changelog for 1.20.0
  doc/releases.md
Labels: type: docs

#6446 compat: Dask 2024.11
  pyproject.toml
Labels: type: compatibility

#6442 docs: Fix wrong variable name
  examples/gallery/demos/bokeh/choropleth_data_link.ipynb
  examples/gallery/demos/bokeh/texas_choropleth_example.ipynb
  examples/gallery/demos/matplotlib/texas_choropleth_example.ipynb
  examples/user_guide/Linked_Brushing.ipynb
Labels: type: docs
