Repository holoviz/holoviews, pull requests merged in 2024-06, with the labels that each got.

#6243 Document subcoordinate_group_ranges by extending the EEG Viewer demo
  doc/conf.py
  examples/gallery/demos/bokeh/eeg_viewer.ipynb
  examples/gallery/demos/bokeh/multichannel_timeseries_viewer.ipynb
Labels: type: docs

#6257 Add support for cticks
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/util.py
  holoviews/plotting/plot.py
  holoviews/tests/plotting/bokeh/test_elementplot.py
Labels: type: enhancement

#6253 Update dependencies
  doc/install.md
  holoviews/core/data/pandas.py
  holoviews/core/util.py
  holoviews/operation/timeseries.py
  holoviews/plotting/renderer.py
  holoviews/util/transform.py
  pixi.toml
  pyproject.toml
  scripts/conda/recipe/meta.yaml
Labels: type: maintenance

#6263 Update to support cudf 2024.06
  holoviews/core/data/cudf.py
  pixi.toml
Labels: type: compatibility

#6258 fix vectorfield hover
  holoviews/plotting/bokeh/chart.py
  holoviews/tests/plotting/bokeh/test_vectorfieldplot.py
Labels: type: bug

#6259 Test with dask-expr
  holoviews/tests/conftest.py
  holoviews/tests/core/data/base.py
  holoviews/tests/core/data/test_daskinterface.py
  holoviews/tests/core/data/test_spatialpandas.py
  holoviews/tests/element/test_selection.py
  holoviews/tests/utils.py
  pixi.toml
  pyproject.toml
Labels: type: maintenance

#6216 Use the new conda package format
  .github/workflows/build.yaml
  scripts/conda/build.sh
Labels: type: maintenance

#6002 Add scalebar support
  doc/conf.py
  examples/reference/features/assets/pollen.png
  examples/reference/features/bokeh/Scalebar.ipynb
  examples/reference/features/bokeh/table_hooks_example.ipynb
  holoviews/plotting/bokeh/element.py
  holoviews/tests/plotting/bokeh/test_elementplot.py
Labels: type: feature, czi

#5920 plotly title font size fix
  holoviews/plotting/plotly/element.py
  holoviews/tests/plotting/plotly/test_elementplot.py
Labels: type: enhancement

#6265 Hold rendering until a plot has been fully updated
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/util.py
Labels: type: enhancement

#6256 Ensure Range streams and RangeToolLink respect subcoordinate axis range
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/links.py
  holoviews/plotting/plot.py
  holoviews/tests/plotting/bokeh/test_callbacks.py
  holoviews/tests/ui/bokeh/test_callback.py
Labels: type: bug

#6262 Make Dimension.label source of truth for Dimension identity
  examples/user_guide/01-Annotating_Data.ipynb
  examples/user_guide/08-Tabular_Datasets.ipynb
  holoviews/core/dimension.py
  holoviews/core/pprint.py
  holoviews/plotting/bokeh/chart.py
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/graphs.py
  holoviews/plotting/bokeh/hex_tiles.py
  holoviews/plotting/bokeh/path.py
  holoviews/plotting/bokeh/sankey.py
  holoviews/plotting/bokeh/stats.py
  holoviews/plotting/mixins.py
  holoviews/plotting/mpl/chart.py
  holoviews/plotting/mpl/graphs.py
  holoviews/plotting/mpl/heatmap.py
  holoviews/plotting/mpl/raster.py
  holoviews/plotting/mpl/sankey.py
  holoviews/plotting/plot.py
  holoviews/plotting/plotly/chart.py
  holoviews/plotting/util.py
  holoviews/tests/plotting/bokeh/test_layoutplot.py
Labels: type: enhancement

#6209 Allow subcoordinates to be drawn from NdOverlay dimensions
  holoviews/plotting/bokeh/element.py
  holoviews/tests/plotting/bokeh/test_subcoordy.py
Labels: type: enhancement

#6245 Fix pickling state
  holoviews/core/dimension.py
  holoviews/tests/core/test_dimensioned.py
Labels: type: bug

#6269 Fix colab
  holoviews/plotting/renderer.py
Labels: type: bug

#6273 Use playwright from the Microsoft channel
  pixi.toml
Labels: type: compatibility

#6272 Disable batching when subcoordinate_y is enabled
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/plot.py
  holoviews/tests/core/test_layers.py
  holoviews/tests/plotting/bokeh/test_overlayplot.py
Labels: type: bug

#6271 Ensure downsample works with non-contiguous arrays
  holoviews/operation/downsample.py
  holoviews/tests/operation/test_downsample.py
Labels: type: bug

#6274 Fix issue with range lookups in (y)-axis creation
  holoviews/plotting/bokeh/element.py
  holoviews/tests/plotting/bokeh/test_overlayplot.py
Labels: type: bug

#6278 Maintenance
  .pre-commit-config.yaml
  pyproject.toml
Labels: type: maintenance

#6264 Fix imports for the multichan ts viewer demo
  examples/gallery/demos/bokeh/multichannel_timeseries_viewer.ipynb
Labels: type: docs

#6283 Correctly handle y/xaxis=True/False/None
  holoviews/plotting/bokeh/element.py
  holoviews/tests/plotting/bokeh/test_elementplot.py
Labels: type: bug

#6282 Fix hover label
  holoviews/plotting/bokeh/element.py
  holoviews/tests/plotting/bokeh/test_curveplot.py
Labels: type: bug

#6284 Update changelog for 1.19.0
  doc/releases.md
Labels: type: docs

#6287 Update pre-commit and conda-build script
  .pre-commit-config.yaml
  scripts/conda/build.sh
Labels: type: maintenance

#6291 Update hatch options to match other packages
  .pre-commit-config.yaml
  doc/_static/css/custom.css
  holoviews/tests/core/data/test_daskinterface.py
  pyproject.toml
Labels: type: maintenance

#6293 Update hv.show_versions with more relevant packages
  holoviews/util/_versions.py
Labels: type: maintenance

#6267 Bokeh 3.5 compability and remove numpy2 environment
  .github/workflows/test.yaml
  pixi.toml
  scripts/download_data.py
Labels: type: compatibility

#6299 Ensure no auto index is created when a kdim is part of a multi index
  holoviews/core/data/pandas.py
  holoviews/tests/core/data/test_pandasinterface.py
Labels: type: bug
