Repository holoviz/holoviews, pull requests merged in 2024-10, with the labels that each got.

#6391 Handle dask groupby warning
  holoviews/core/data/dask.py
  holoviews/core/util.py
  pyproject.toml
Labels: type: compatibility

#6402 ci: Fix solve for core test
  pixi.toml
Labels: type: maintenance

#6405 chore: Update pre-commit
  .pre-commit-config.yaml
Labels: type: maintenance

#6409 compat: cuDF 24.10
  pixi.toml
Labels: type: compatibility

#6389 Ensure proper cleanup of stream subscribers
  holoviews/plotting/bokeh/plot.py
  holoviews/plotting/plot.py
  holoviews/tests/plotting/bokeh/test_plot.py
  holoviews/tests/plotting/plotly/test_plot.py
Labels: type: bug

#6407 Handle datetime selection in cuDF interface
  holoviews/core/data/cudf.py
Labels: type: bug

#6403 enh: Add Scalebar support for subcoordinate_y plots
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/util.py
  holoviews/tests/plotting/bokeh/test_elementplot.py
Labels: type: enhancement

#6412 enh: Rename `index` column to `__index__` and remove old version check
  holoviews/operation/datashader.py
  holoviews/tests/operation/test_datashader.py
Labels: type: enhancement

#6336 fix a problem where linked selections were resulting in repeated columns
  holoviews/element/selection.py
  holoviews/tests/element/test_selection.py
Labels: type: bug

#6413 refactor: Align version check
  examples/conftest.py
  holoviews/core/data/dask.py
  holoviews/core/data/ibis.py
  holoviews/core/data/pandas.py
  holoviews/core/util.py
  holoviews/element/util.py
  holoviews/operation/element.py
  holoviews/plotting/bokeh/__init__.py
  holoviews/plotting/bokeh/annotation.py
  holoviews/plotting/bokeh/callbacks.py
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/links.py
  holoviews/plotting/bokeh/raster.py
  holoviews/plotting/bokeh/util.py
  holoviews/plotting/mpl/__init__.py
  holoviews/plotting/mpl/chart.py
  holoviews/plotting/mpl/chart3d.py
  holoviews/plotting/mpl/element.py
  holoviews/plotting/mpl/raster.py
  holoviews/plotting/mpl/stats.py
  holoviews/plotting/mpl/util.py
  holoviews/plotting/plotly/__init__.py
  holoviews/plotting/renderer.py
  holoviews/plotting/util.py
  holoviews/tests/core/data/test_daskinterface.py
  holoviews/tests/core/data/test_ibisinterface.py
  holoviews/tests/core/test_dimensions.py
  holoviews/tests/element/test_annotations.py
  holoviews/tests/element/test_comparisondimension.py
  holoviews/tests/plotting/bokeh/test_annotationplot.py
  holoviews/tests/plotting/bokeh/test_elementplot.py
  holoviews/tests/plotting/bokeh/test_rasterplot.py
  holoviews/tests/plotting/bokeh/test_subcoordy.py
  holoviews/tests/plotting/matplotlib/test_annotationplot.py
  holoviews/tests/plotting/matplotlib/test_boxwhisker.py
  holoviews/tests/plotting/matplotlib/test_graphplot.py
  holoviews/tests/plotting/matplotlib/test_heatmapplot.py
  holoviews/tests/plotting/matplotlib/test_plot.py
  holoviews/tests/plotting/matplotlib/test_quadmeshplot.py
  holoviews/tests/plotting/matplotlib/test_violinplot.py
  holoviews/tests/test_streams.py
  holoviews/tests/ui/bokeh/test_callback.py
  scripts/download_data.py
Labels: type: enhancement

#6415 Fixes to ensure streams are correctly mapped to plots
  holoviews/plotting/plot.py
  holoviews/plotting/util.py
  holoviews/tests/plotting/test_plotutils.py
Labels: type: bug

#6390 Support async callbacks for popup
  holoviews/plotting/bokeh/callbacks.py
  holoviews/tests/plotting/bokeh/test_callbacks.py
  holoviews/tests/ui/bokeh/test_callback.py
  pixi.toml
  pyproject.toml
Labels: type: enhancement

#6418 ci: Use Microsoft channel for pytest-playwright
  pixi.toml
Labels: type: maintenance

#6417 fix: Don't remove ds_version yet
  holoviews/operation/datashader.py
Labels: type: bug

#6414 Add popup position and anchor
  examples/user_guide/13-Custom_Interactivity.ipynb
  holoviews/plotting/bokeh/callbacks.py
  holoviews/streams.py
  holoviews/tests/ui/bokeh/test_callback.py
Labels: type: enhancement

#6419 Lock closed issues/prs
  .github/workflows/lock.yaml
Labels: type: maintenance

#6421 Fixed broken sentences and references to Bokeh in the mpl guide
  examples/user_guide/Plotting_with_Matplotlib.ipynb
Labels: type: docs

#6425 ci: add pytest-asyncio to test
  .pre-commit-config.yaml
  pyproject.toml
Labels: type: enhancement

#6426 ci: Fix check_latest_packages sorting
  scripts/check_latest_packages.py
Labels: type: enhancement

#6423 refactor: Remove try/except import for popup functionality
  holoviews/plotting/bokeh/callbacks.py
Labels: type: enhancement

#6427 Update lock.yaml
  .github/workflows/lock.yaml
Labels: type: maintenance

#6428 Fix bar width for small xdiff
  holoviews/plotting/bokeh/chart.py
  holoviews/tests/plotting/bokeh/test_barplot.py
Labels: type: bug
