Repository holoviz/holoviews, pull requests merged in 2024-07, with the labels that each got.

#6307 comp(matplotlib): Add compatibility with Matplotlib 3.9
  holoviews/plotting/mpl/chart.py
  holoviews/plotting/mpl/stats.py
  holoviews/plotting/mpl/util.py
  holoviews/tests/plotting/matplotlib/test_annotationplot.py
  holoviews/tests/plotting/matplotlib/test_boxwhisker.py
  holoviews/tests/plotting/matplotlib/test_violinplot.py
  pyproject.toml
Labels: type: compatibility

#6301 Fix bar with one value in it
  holoviews/plotting/bokeh/chart.py
  holoviews/tests/plotting/bokeh/test_barplot.py
Labels: type: bug

#6297 Set zIndex of Popup to 1000
  holoviews/plotting/bokeh/callbacks.py
Labels: type: bug

#6304 fix: Handle boolean in by Bars
  holoviews/plotting/bokeh/element.py
  holoviews/tests/plotting/bokeh/test_barplot.py
Labels: type: bug

#6306 comp(pandas): Remove observed FutureWarning
  holoviews/core/data/pandas.py
  holoviews/tests/core/data/test_pandasinterface.py
Labels: type: compatibility

#6290 Also check for pd.NA in is_nan
  holoviews/core/util.py
  holoviews/tests/core/test_utils.py
  holoviews/tests/plotting/bokeh/test_annotationplot.py
Labels: type: bug

#6294 Add color to bars for Plotly
  holoviews/plotting/plotly/chart.py
  holoviews/tests/plotting/plotly/test_barplot.py
Labels: type: enhancement

#6309 Lazy load dask.dataframe in datashader.py
  holoviews/core/util.py
  holoviews/operation/datashader.py
Labels: type: compatibility

#6310 Add changelog for 1.19.1 release
  doc/releases.md
Labels: type: docs

#6296 Update ruff to 0.5.0
  .pre-commit-config.yaml
  holoviews/annotators.py
  holoviews/core/accessors.py
  holoviews/core/data/spatialpandas.py
  holoviews/core/options.py
  holoviews/core/pprint.py
  holoviews/ipython/archive.py
  holoviews/ipython/magics.py
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/links.py
  holoviews/plotting/plot.py
Labels: type: maintenance

#6314 De-parameterize the options Keywords objects
  holoviews/core/options.py
Labels: type: enhancement

#6315 Freeze models while updating plot(s)
  holoviews/plotting/bokeh/util.py
  pixi.toml
Labels: type: enhancement

#6338 Ensure CI version check only tests compatible versions
  scripts/check_latest_packages.py
Labels: type: maintenance

#6344 Update pre-commit and Bokeh 3.5 support for autorange
  .pre-commit-config.yaml
  holoviews/core/accessors.py
  holoviews/core/ndmapping.py
  holoviews/plotting/bokeh/element.py
  holoviews/tests/plotting/matplotlib/test_annotationplot.py
Labels: type: maintenance

#6337 Wrap popup in set_curdoc
  holoviews/plotting/bokeh/callbacks.py
Labels: type: bug

#6346 Fix observed warnings for categorial data
  holoviews/core/data/pandas.py
  holoviews/core/util.py
  holoviews/element/util.py
  holoviews/tests/plotting/bokeh/test_heatmapplot.py
Labels: type: compatibility

#6277 Support hit-tested group-wise wheel zoom renderers for subcoordinate_y
  .gitignore
  examples/assets/data_range.png
  examples/gallery/demos/bokeh/multichannel_timeseries_viewer.ipynb
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/util.py
  holoviews/tests/plotting/bokeh/test_subcoordy.py
Labels: type: enhancement

#6347 Fixes popup being invisible forever after closing once
  holoviews/plotting/bokeh/callbacks.py
  holoviews/tests/ui/bokeh/test_callback.py
Labels: type: bug

#6349 Fix CI
  .gitignore
  pixi.toml
Labels: type: maintenance
