Repository holoviz/holoviews, pull requests merged in 2024-05, with the labels that each got.

#6200 Update documentation and small Pixi improvements
  .gitattributes
  .github/workflows/build.yaml
  .github/workflows/docs.yaml
  .github/workflows/nightly_lock.yaml
  .github/workflows/test.yaml
  README.md
  doc/developer_guide/index.md
  doc/index.md
  doc/index.rst
  doc/install.md
  doc/install.rst
  doc/user_guide/Configuring.md
  doc/user_guide/Installing_and_Configuring.rst
  doc/user_guide/index.rst
  examples/README.md
  examples/user_guide/Installing_and_Configuring.ipynb
  holoviews/core/data/interface.py
  holoviews/core/pprint.py
  holoviews/tests/conftest.py
  holoviews/tests/core/data/test_ibisinterface.py
  holoviews/tests/core/test_options.py
  holoviews/tests/core/test_storeoptions.py
  holoviews/tests/ipython/test_displayhooks.py
  holoviews/tests/ipython/test_notebooks.py
  holoviews/tests/operation/test_operation.py
  holoviews/tests/plotting/bokeh/test_callbacks.py
  holoviews/tests/plotting/bokeh/test_renderer.py
  holoviews/tests/plotting/bokeh/test_utils.py
  holoviews/tests/plotting/matplotlib/__init__.py
  holoviews/tests/plotting/plotly/__init__.py
  holoviews/tests/plotting/test_plotutils.py
  holoviews/tests/test_selection.py
  holoviews/tests/util/test_help.py
  holoviews/tests/util/test_utils.py
  pixi.toml
  pyproject.toml
  scripts/conda/recipe/meta.yaml
  scripts/download_data.py
Labels: type: maintenance

#6213 Use psutil for pytest-xdist logical option
  pixi.toml
Labels: type: maintenance

#6214 General maintenance
  .github/workflows/nightly_lock.yaml
  .pre-commit-config.yaml
  holoviews/annotators.py
  holoviews/core/accessors.py
  holoviews/core/data/array.py
  holoviews/core/data/cudf.py
  holoviews/core/data/dictionary.py
  holoviews/core/data/grid.py
  holoviews/core/data/ibis.py
  holoviews/core/data/interface.py
  holoviews/core/data/multipath.py
  holoviews/core/data/pandas.py
  holoviews/core/data/spatialpandas.py
  holoviews/core/data/xarray.py
  holoviews/core/dimension.py
  holoviews/core/element.py
  holoviews/core/io.py
  holoviews/core/ndmapping.py
  holoviews/core/options.py
  holoviews/core/pprint.py
  holoviews/core/spaces.py
  holoviews/core/tree.py
  holoviews/core/util.py
  holoviews/element/annotation.py
  holoviews/element/graphs.py
  holoviews/element/sankey.py
  holoviews/ipython/__init__.py
  holoviews/ipython/archive.py
  holoviews/operation/datashader.py
  holoviews/operation/stats.py
  holoviews/plotting/bokeh/chart.py
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/graphs.py
  holoviews/plotting/bokeh/links.py
  holoviews/plotting/bokeh/plot.py
  holoviews/plotting/bokeh/tiles.py
  holoviews/plotting/bokeh/util.py
  holoviews/plotting/mpl/element.py
  holoviews/plotting/plot.py
  holoviews/plotting/plotly/__init__.py
  holoviews/plotting/plotly/plot.py
  holoviews/plotting/plotly/tiles.py
  holoviews/plotting/util.py
  holoviews/selection.py
  holoviews/streams.py
  holoviews/util/__init__.py
  holoviews/util/parser.py
  holoviews/util/settings.py
  holoviews/util/transform.py
Labels: type: maintenance

#6220 Clone model if Tool is model
  holoviews/plotting/bokeh/element.py
Labels: type: bug

#6207 Cleanup popup
  holoviews/plotting/bokeh/callbacks.py
  holoviews/tests/ui/bokeh/test_callback.py
Labels: type: enhancement

#6218 Merge CHANGELOG.md and releases.rst
  doc/releases.md
  doc/releases.rst
Labels: type: maintenance

#6217 Add `test-gpu` task
  holoviews/core/data/cudf.py
  holoviews/element/selection.py
  holoviews/tests/conftest.py
  holoviews/tests/core/data/test_cudfinterface.py
  holoviews/tests/element/test_selection.py
  holoviews/tests/operation/test_datashader.py
  holoviews/tests/operation/test_operation.py
  pixi.toml
Labels: type: maintenance

#6219 Update pre-commit prettier repo
  .pre-commit-config.yaml
Labels: type: maintenance

#6227 Add toml formatter
  .pre-commit-config.yaml
  pyproject.toml
Labels: type: maintenance

#6228 Update CSS for documentation
  .pre-commit-config.yaml
  doc/_static/css/custom.css
Labels: type: docs

#6230 Bump minimum version of param to 2.0 and add stream transform
  holoviews/core/accessors.py
  holoviews/core/spaces.py
  holoviews/core/util.py
  holoviews/streams.py
  holoviews/util/__init__.py
  holoviews/util/transform.py
  pixi.toml
  pyproject.toml
Labels: type: enhancement

#6235 General maintenance
  .github/workflows/nightly_lock.yaml
  .pre-commit-config.yaml
  doc/index.md
Labels: type: maintenance

#6145 Allow Bars to be plotted on continuous axes
  examples/reference/elements/bokeh/Bars.ipynb
  examples/reference/elements/matplotlib/Bars.ipynb
  examples/reference/elements/plotly/Bars.ipynb
  holoviews/plotting/bokeh/chart.py
  holoviews/plotting/bokeh/plot.py
  holoviews/plotting/mixins.py
  holoviews/plotting/mpl/chart.py
  holoviews/plotting/plotly/chart.py
  holoviews/plotting/plotly/element.py
  holoviews/tests/plotting/bokeh/test_barplot.py
  holoviews/tests/plotting/matplotlib/test_barplot.py
  holoviews/tests/plotting/plotly/test_barplot.py
Labels: type: enhancement

#6134 Add min_interval and max_interval to the RangeToolLink
  examples/gallery/demos/bokeh/eeg_viewer.ipynb
  holoviews/plotting/bokeh/links.py
  holoviews/plotting/links.py
  holoviews/tests/conftest.py
  holoviews/tests/ui/bokeh/test_links.py
Labels: type: enhancement

#6221 Don't error on TypeError in DaskInterface when sorting
  holoviews/core/data/dask.py
Labels: type: bug

#5958 Add support for rasterizing geopandas dataframes directly
  holoviews/operation/datashader.py
Labels: type: enhancement

#6196 Allow options for non-enabled backends
  holoviews/core/dimension.py
  holoviews/util/__init__.py
Labels: type: enhancement

#6024 Support ImageStack in dynspread
  holoviews/operation/datashader.py
  holoviews/tests/operation/test_datashader.py
Labels: type: enhancement

#6239 No nighly lock for forks
  .github/workflows/nightly_lock.yaml
Labels: type: maintenance

#6246 Fix links
  examples/README.md
  examples/user_guide/Deploying_Bokeh_Apps.ipynb
Labels: type: docs

#6238 Numpy 2.0 compability
  .github/workflows/test.yaml
  examples/conftest.py
  holoviews/core/sheetcoords.py
  holoviews/core/util.py
  holoviews/tests/core/test_dimensions.py
  holoviews/tests/element/test_comparisondimension.py
  holoviews/tests/test_streams.py
  pixi.toml
  pyproject.toml
Labels: type: compatibility

#6249 Update pre-commit
  .pre-commit-config.yaml
  examples/reference/elements/bokeh/HexTiles.ipynb
  examples/reference/elements/matplotlib/HexTiles.ipynb
  pyproject.toml
Labels: type: maintenance

#6234 Parallelize unit test
  holoviews/tests/conftest.py
  holoviews/tests/core/data/test_imageinterface.py
  holoviews/tests/core/test_dimensioned.py
  holoviews/tests/core/test_options.py
  holoviews/tests/ipython/test_displayhooks.py
  holoviews/tests/ipython/test_magics.py
  holoviews/tests/plotting/bokeh/test_callbacks.py
  holoviews/tests/plotting/bokeh/test_curveplot.py
  holoviews/tests/plotting/bokeh/test_server.py
  holoviews/tests/plotting/matplotlib/test_renderer.py
  holoviews/tests/plotting/plotly/test_renderer.py
  holoviews/tests/util/test_utils.py
  pixi.toml
Labels: tag: component: testing, type: maintenance

#6250 Fix `hv.help` if `Info.store` is `None`
  holoviews/core/options.py
  holoviews/tests/util/test_help.py
Labels: type: bug

#6251 Move environment variables into Pixi.toml
  .github/workflows/docs.yaml
  .github/workflows/test.yaml
  pixi.toml
  pyproject.toml
Labels: type: maintenance

#4898 Change how upper limit is taken for color_levels
  holoviews/plotting/util.py
  holoviews/tests/plotting/bokeh/test_pathplot.py
  holoviews/tests/plotting/test_plotutils.py
Labels: type: bug
