Repository holoviz/holoviews, pull requests merged in 2024-08, with the labels that each got.

#6351 🎨 Just improving logic structure.
  holoviews/core/data/xarray.py
Labels: type: enhancement

#6358 Update gpu pins
  .pre-commit-config.yaml
  holoviews/tests/ipython/test_notebooks.py
  pixi.toml
  pyproject.toml
Labels: type: maintenance

#6341 Adds Bokeh 3.5 enhancements to RangeToolLink
  holoviews/plotting/bokeh/links.py
  holoviews/plotting/links.py
  pixi.toml
Labels: tag: backend: bokeh, type: enhancement

#6363 Update pre-commit and add nomkl
  .github/workflows/build.yaml
  .pre-commit-config.yaml
  examples/conftest.py
  holoviews/element/graphs.py
  holoviews/plotting/mpl/tabular.py
  pixi.toml
Labels: type: maintenance

#6367 Disable simple id in Notebook
  holoviews/ipython/__init__.py
Labels: type: bug
