Repository holoviz/holoviews, pull requests merged in 2024-04, with the labels that each got.

#5978 Bump CI tests to use Python 3.12
  .github/workflows/test.yaml
Labels: type: compatibility

#6172 Improve groupby behavior for operation histogram
  holoviews/operation/element.py
  holoviews/tests/operation/test_operation.py
Labels: type: bug

#6174 Improve autocompletion for lazy module
  .github/workflows/test.yaml
  holoviews/__init__.py
  holoviews/tests/plotting/bokeh/test_callbacks.py
Labels: type: enhancement

#6179 minor typo in customizing plots
  examples/user_guide/Customizing_Plots.ipynb
Labels: type: docs

#6173 Ensure plot ranges for all renderers are combined in auto-ranging
  holoviews/plotting/bokeh/element.py
  holoviews/tests/ui/bokeh/test_autorange.py
Labels: type: bug

#6195 Ensure that the downsample algorithm m4 n_out is always a multiple of 4
  holoviews/operation/downsample.py
Labels: type: bug

#6194 subcoordinate_y: reverse the renderers by default
  holoviews/plotting/bokeh/element.py
  holoviews/tests/plotting/bokeh/test_subcoordy.py
Labels: type: enhancement

#6181 Add `xyzservices` as a test dependency
  setup.py
Labels: type: maintenance

#6180 Add hover_tooltips, hover_mode, hover_formatters opts to easily modify hover
  examples/gallery/demos/bokeh/html_hover_tooltips.ipynb
  examples/user_guide/Plotting_with_Bokeh.ipynb
  holoviews/plotting/bokeh/element.py
  holoviews/tests/ui/bokeh/test_hover.py
Labels: type: enhancement

#6056 Expose setting hard navigable bounds
  examples/user_guide/Plotting_with_Bokeh.ipynb
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/plot.py
  holoviews/tests/plotting/bokeh/test_elementplot.py
Labels: tag: backend: bokeh, type: enhancement, czi

#6122 Add a zoom tool per subcoordinate_y group
  holoviews/plotting/bokeh/element.py
  holoviews/tests/plotting/bokeh/test_subcoordy.py
Labels: type: enhancement

#6168 Add support for popups on selection streams
  examples/user_guide/13-Custom_Interactivity.ipynb
  holoviews/plotting/bokeh/callbacks.py
  holoviews/streams.py
  holoviews/tests/ui/bokeh/test_callback.py
Labels: type: feature

#6061 Implement support for retaining Pandas index
  holoviews/core/data/ibis.py
  holoviews/core/data/pandas.py
  holoviews/tests/core/data/test_pandasinterface.py
  holoviews/tests/operation/test_downsample.py
Labels: type: enhancement

#6182 Switch to Pixi for development / CI and hatchling for build system
  .github/workflows/build.yaml
  .github/workflows/docs.yaml
  .github/workflows/nightly_lock.yaml
  .github/workflows/test.yaml
  .gitignore
  MANIFEST.in
  conda.recipe/README.md
  conda.recipe/meta.yaml
  doc/conf.py
  doc/developer_guide/index.md
  doc/index.rst
  dodo.py
  holoviews/__init__.py
  holoviews/__version.py
  holoviews/tests/util/test_utils.py
  pixi.toml
  pyproject.toml
  scripts/build_conda.sh
  scripts/conda/build.sh
  scripts/conda/recipe/meta.yaml
  scripts/download_data.py
  scripts/download_data.sh
  setup.cfg
  setup.py
  tox.ini
Labels: type: maintenance

#6199 Fix flaky pop up ui tests
  holoviews/tests/ui/bokeh/test_callback.py
Labels: type: bug

#6190 subcoordinate_y: respect `ylim`
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/plot.py
  holoviews/tests/plotting/bokeh/test_subcoordy.py
Labels: type: bug

#6124 Add operation for group-wise normalisation
  holoviews/operation/normalization.py
  holoviews/plotting/bokeh/element.py
  holoviews/tests/plotting/bokeh/test_subcoordy.py
Labels: type: enhancement

#6212 Bug fix for player example pause button
  examples/reference/apps/bokeh/player.py
Labels: type: bug
