Repository holoviz/holoviews, pull requests merged in 2024-01, with the labels that each got.

#6070 Skip Deploying_Bokeh_Apps.ipynb on Windows
  examples/conftest.py
Labels: type: maintenance

#6051 Zoom tools automatically vertically scaled on subcoordinate_y overlays
  holoviews/plotting/bokeh/element.py
  holoviews/tests/plotting/bokeh/test_subcoordy.py
Labels: type: enhancement

#6072 Use importlib.version to remove import from show_versions
  holoviews/util/_versions.py
Labels: type: maintenance

#6059 Use tsdownsample library for downsampling if available
  holoviews/operation/downsample.py
Labels: type: enhancement

#6074 Update to work with Pandas 2.2 release candidate
  holoviews/core/data/xarray.py
  holoviews/element/selection.py
  holoviews/tests/core/data/test_pandasinterface.py
  holoviews/tests/core/test_apply.py
  holoviews/tests/element/test_selection.py
  holoviews/tests/operation/test_datashader.py
  holoviews/tests/plotting/bokeh/test_callbacks.py
  pyproject.toml
Labels: type: compatibility

#6077 Disable always on warnings
  holoviews/util/warnings.py
Labels: type: maintenance

#6076 Add Comm on_open handler to initialize the server comm
  holoviews/plotting/renderer.py
Labels: type: compatibility

#6078 Fix tests suite because of Pandas 2.2
  .pre-commit-config.yaml
  README.md
  holoviews/__init__.py
  holoviews/element/graphs.py
  holoviews/tests/plotting/bokeh/test_renderer.py
  pyproject.toml
Labels: type: compatibility

#6081 Update show_versions to use package name
  holoviews/util/_versions.py
Labels: type: maintenance

#6083 Add test for downsample algorithms
  holoviews/tests/conftest.py
  holoviews/tests/element/test_selection.py
  holoviews/tests/operation/test_downsample.py
  setup.py
Labels: type: enhancement

#6017 Add viewport downsample algorithm
  holoviews/core/data/cudf.py
  holoviews/core/data/dask.py
  holoviews/core/data/ibis.py
  holoviews/core/data/interface.py
  holoviews/operation/downsample.py
  holoviews/plotting/bokeh/callbacks.py
  holoviews/plotting/bokeh/plot.py
  holoviews/streams.py
  holoviews/tests/core/data/base.py
  holoviews/tests/core/data/test_cudfinterface.py
  holoviews/tests/core/data/test_ibisinterface.py
  holoviews/tests/operation/test_downsample.py
Labels: type: enhancement

#6085 Del frame after stack level is found
  holoviews/util/warnings.py
  scripts/check_latest_packages.py
Labels: type: bug

#6088 Add downloads badges
  README.md
Labels: type: maintenance
