Repository holoviz/holoviews, pull requests merged in 2024-03, with the labels that each got.

#6144 General maintenance
  .github/workflows/docs.yaml
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  scripts/check_latest_packages.py
  scripts/download_data.sh
  setup.py
Labels: type: maintenance

#6141 Update merge_tool
  holoviews/plotting/bokeh/util.py
Labels: type: bug

#6146 General maintenance
  .github/workflows/docs.yaml
  .github/workflows/test.yaml
  setup.py
Labels: type: maintenance

#6147 Simplify dev pull
  .github/workflows/test.yaml
Labels: type: maintenance

#6149 Add dask setting to disable query-planning for now
  holoviews/tests/conftest.py
Labels: type: compatibility

#6152 Bump ruff and remove Bokeh rc workarounds
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  holoviews/core/dimension.py
  holoviews/core/io.py
  holoviews/element/raster.py
  holoviews/ipython/archive.py
  holoviews/operation/datashader.py
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/plot.py
  holoviews/plotting/plotly/element.py
  holoviews/plotting/util.py
  holoviews/streams.py
  holoviews/tests/utils.py
  holoviews/util/__init__.py
  scripts/check_latest_packages.py
Labels: type: maintenance

#6153 Don't raise KeyError if options don't contain None
  holoviews/plotting/plot.py
Labels: type: bug

#6155 Force vdims to strings for ImageStack
  holoviews/operation/datashader.py
  holoviews/tests/operation/test_datashader.py
Labels: type: bug

#6031 Package update - build and publish
  .github/workflows/build.yaml
  conda.recipe/meta.yaml
  scripts/build_conda.sh
Labels: type: maintenance

#6157 Update server tests to simulate loaded event
  holoviews/tests/plotting/bokeh/test_callbacks.py
  holoviews/tests/plotting/bokeh/test_server.py
Labels: type: compatibility

#6025 Support dictionary cmaps for ImageStack
  holoviews/plotting/bokeh/raster.py
  holoviews/tests/plotting/bokeh/test_rasterplot.py
Labels: type: enhancement

#6163 Update holoviz_tasks version
  .github/workflows/docs.yaml
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  examples/conftest.py
  holoviews/tests/plotting/matplotlib/test_renderer.py
Labels: type: maintenance
