Repository holoviz/holoviews, pull requests merged in 2024-09, with the labels that each got.

#6371 Ibis 9.5 compatibility
  holoviews/core/data/ibis.py
  holoviews/operation/element.py
Labels: type: compatibility

#6373 Ensure pixel_ratio is applied when computing resampling coordinates
  holoviews/operation/resample.py
  holoviews/tests/operation/test_datashader.py
Labels: type: bug

#6376 Add support for rendering H/V Line and Span on multi_y
  holoviews/plotting/bokeh/annotation.py
  holoviews/tests/plotting/bokeh/test_annotationplot.py
Labels: type: bug

#6378 Drop z dimension from ImageStack DataArray before shading
  holoviews/core/data/xarray.py
  holoviews/operation/datashader.py
  holoviews/tests/operation/test_datashader.py
Labels: type: bug

#6383 Test Python 3.13 rc
  pixi.toml
  pyproject.toml
Labels: type: compatibility

#6365 Improve datetime support for hv.Bars
  holoviews/plotting/bokeh/chart.py
  holoviews/plotting/mixins.py
  holoviews/plotting/mpl/chart.py
  holoviews/tests/plotting/bokeh/test_barplot.py
  holoviews/tests/plotting/matplotlib/test_barplot.py
Labels: type: bug

#6369 General maintenance
  .github/workflows/build.yaml
  .github/workflows/docs.yaml
  .github/workflows/nightly_lock.yaml
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  holoviews/__init__.py
Labels: type: maintenance

#6375 Add `sublabel_index` and `sublabel_skip` option for matplotlib backend
  holoviews/plotting/mpl/plot.py
  holoviews/tests/plotting/matplotlib/test_layoutplot.py
Labels: type: enhancement

#6377 Handle datetimes and empty selections better for inspect operations
  holoviews/operation/datashader.py
  holoviews/tests/operation/test_datashader.py
Labels: type: enhancement

#6318 Improve following behavior when streaming
  holoviews/plotting/bokeh/element.py
  holoviews/plotting/bokeh/plot.py
  holoviews/streams.py
  holoviews/tests/plotting/bokeh/test_overlayplot.py
  holoviews/tests/test_streams.py
Labels: type: enhancement

#6392 Fix typo in the changelog
  doc/releases.md
Labels: type: docs

#6393 CI: Fix bash call
  .github/workflows/build.yaml
  .github/workflows/docs.yaml
  .github/workflows/test.yaml
Labels: type: maintenance

#6398 ci: Add collector to avoid if statements
  .github/workflows/test.yaml
Labels: type: maintenance

#6399 ci: Fix conda publish
  .github/workflows/build.yaml
Labels: type: maintenance
